In [ ]:
!pip install pymysql pandas sqlalchemy

Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.10/dist-packages (2.0.35)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 1.6 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
user = "@@@@@"
password = "@@@@@@"
host = "@@@@@@@"
database = "@@@@"

In [ ]:
conn = create_engine(f"mysql+pymysql://{user}:{password}@{host}/{database}")

In [ ]:
conn = create_engine(f"mysql+pymysql://aluno:@@@@@@@@@@@@@@@@@@@")

In [ ]:
conn

Engine(mysql+pymysql://%28%27aluno%27%2C%29:***@('107.180.0.110',)/me315)

In [ ]:
pd.read_sql("""
    SELECT * FROM VaiCorinthians
    LIMIT 5
    """, conn)

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
pd.read_sql(
    """
     SELECT Species, AVG(`Sepal.Length`) AS media
     FROM VaiCorinthians
     GROUP BY Species
""", conn)

      Species  media
0      setosa  5.006
1  versicolor  5.936
2   virginica  6.588

In [ ]:
pd.read_sql("""
     SELECT Species,
           MAX(`Sepal.Length`),
           MAX(`Sepal.Width`),
           MAX(`Petal.Length`),
           MAX(`Petal.Width`)
     FROM VaiCorinthians
     GROUP BY Species
     """,
     conn)

,Species,MAX(`Sepal.Length`),MAX(`Sepal.Width`),MAX(`Petal.Length`),MAX(`Petal.Width`)
0,setosa,5.8,4.4,1.9,0.6
1,versicolor,7.0,3.4,5.1,1.8
2,virginica,7.9,3.8,6.9,2.5