In [ ]:
import polars as pl
import sqlite3

In [ ]:

import polars as pl
import sqlite3
conn = sqlite3.connect('imdb.db')

basics_df_pd = basics_df.to_pandas()
ratings_df_pd = ratings_df.to_pandas()
principals_df_pd = principals_df.to_pandas()

basics_df_pd.to_sql('basics', conn, if_exists='replace', index=False)
ratings_df_pd.to_sql('ratings', conn, if_exists='replace', index=False)
principals_df_pd.to_sql('principals', conn, if_exists='replace', index=False)

conn.close()

In [ ]:
conn = sqlite3.connect('/content/drive/MyDrive/4º Semestre/ME315/banco de dado /lab 9/movies.sqlite3')

In [ ]:
basics = pl.read_csv("/content/drive/MyDrive/4º Semestre/ME315/banco de dado /lab 9/title.basics0.tsv.gz",
                     separator= "\t", null_values= "\\N")
principals = pl.read_csv("/content/drive/MyDrive/4º Semestre/ME315/banco de dado /lab 9/title.principals0.tsv.gz",
                     separator= "\t", null_values= "\\N", n_rows= 2000000)
ratings = pl.read_csv("/content/drive/MyDrive/4º Semestre/ME315/banco de dado /lab 9/title.ratings.tsv.gz",
                     separator= "\t", null_values= "\\N")

In [ ]:
pl.read_database("""
SELECT originalTitle, averageRating, numVotes
FROM ratings
INNER JOIN basics ON ratings.tconst = basics.tconst
ORDER BY averageRating DESC, numVotes
LIMIT 5
""", conn)

shape: (5, 3)
┌──────────────────────┬───────────────┬──────────┐
│ originalTitle        ┆ averageRating ┆ numVotes │
│ ---                  ┆ ---           ┆ ---      │
│ str                  ┆ f64           ┆ f64      │
╞══════════════════════╪═══════════════╪══════════╡
│ A View of Bosnia     ┆ 10.0          ┆ 5.0      │
│ Foto Novelas: Mangas ┆ 10.0          ┆ 5.0      │
│ A Boy and His Hand   ┆ 10.0          ┆ 5.0      │
│ Whoosh               ┆ 10.0          ┆ 5.0      │
│ Empty Boxes          ┆ 10.0          ┆ 5.0      │
└──────────────────────┴───────────────┴──────────┘

In [ ]:
pl.read_database("""
SELECT genres, COUNT(*) AS n FROM ratings
INNER JOIN basics ON ratings.tconst = basics.tconst
WHERE averageRating > 8 AND titleType = 'movie'
GROUP BY genres
ORDER BY n DESC
LIMIT 1
""", conn)

shape: (1, 2)
┌─────────────┬──────┐
│ genres      ┆ n    │
│ ---         ┆ ---  │
│ str         ┆ i64  │
╞═════════════╪══════╡
│ Documentary ┆ 7206 │
└─────────────┴──────┘

In [ ]:
pl.read_database("""
  SELECT nconst, COUNT(*) AS n FROM ratings
  INNER JOIN basics ON ratings.tconst = basics.tconst
  INNER JOIN principals ON basics.tconst = principals.tconst
  WHERE averageRating > 7.5 AND titleType = 'movie' AND category IN ('actor', 'actress')
  GROUP BY nconst
  ORDER BY n DESC
  LIMIT 3
""", conn)