In [ ]:
import polars as pl

In [ ]:
basics = pl.read_csv("/content/drive/MyDrive/4º Semestre/ME315/banco de dado /lab 9/title.basics0.tsv.gz",
                     separator= "\t", null_values= "\\N")

In [ ]:
principals = pl.read_csv("/content/drive/MyDrive/4º Semestre/ME315/banco de dado /lab 9/title.principals0.tsv.gz",
                     separator= "\t", null_values= "\\N", n_rows= 2000000)

In [ ]:
ratings = pl.read_csv("/content/drive/MyDrive/4º Semestre/ME315/banco de dado /lab 9/title.ratings.tsv.gz",
                     separator= "\t", null_values= "\\N")

1. Quais são os 5 filmes com as maiores notas (averageRating)? Apresente uma solução capaz de desempatar os filmes baseando-se no número de votos recebidos.

In [ ]:
(
    ratings.sort(["averageRating", "numVotes"], descending = True).head(5)
    .join(basics, on = "tconst", how = "inner")
    .select(["originalTitle", "averageRating", "numVotes"])
)

shape: (5, 3)
┌─────────────────────────────────┬───────────────┬──────────┐
│ originalTitle                   ┆ averageRating ┆ numVotes │
│ ---                             ┆ ---           ┆ ---      │
│ str                             ┆ f64           ┆ i64      │
╞═════════════════════════════════╪═══════════════╪══════════╡
│ Ozymandias                      ┆ 10.0          ┆ 228900   │
│ Kadifeyi Kesfet                 ┆ 10.0          ┆ 2904     │
│ Inci Koleksiyonunu Kesfet!      ┆ 10.0          ┆ 2812     │
│ Tatilde CUK Oturur Mukemmel Du… ┆ 10.0          ┆ 2878     │
│ DeFacto Kis Festivali           ┆ 10.0          ┆ 2676     │
└─────────────────────────────────┴───────────────┴──────────┘

In [ ]:
(
    ratings.filter(pl.col("averageRating") > 8)
    .join(basics.filter(pl.col("titleType") == "movie"),
          on = "tconst", how = "inner")
    .group_by("genres").len()
    .sort("len", descending = True)
    .head(1)

)

shape: (1, 2)
┌─────────────┬──────┐
│ genres      ┆ len  │
│ ---         ┆ ---  │
│ str         ┆ u32  │
╞═════════════╪══════╡
│ Documentary ┆ 7206 │
└─────────────┴──────┘

In [ ]:
(
    ratings.filter(pl.col("averageRating") > 7.5)
    .join(basics.filter(pl.col("titleType") == "movie"),
          on = "tconst", how = "inner")
    .select("tconst")
    .join(principals.filter(pl.col("category"). is_in(["actor", "actress"]))
    , on = "tconst", how = "inner")
    .group_by("nconst").len()
    .sort("len", descending = True).head(3)
)

shape: (3, 2)
┌───────────┬─────┐
│ nconst    ┆ len │
│ ---       ┆ --- │
│ str       ┆ u32 │
╞═══════════╪═════╡
│ nm0001536 ┆ 34  │
│ nm0793766 ┆ 25  │
│ nm0352032 ┆ 21  │
└───────────┴─────┘